### PR TITLE
Dev rx string

### PR DESCRIPTION
**Pull request by dmi3kno**
This is significant rewrite of pretty much all functions. Test are running fine, but some examples in the documentation are failing. We can fix those later. Lets get conceptually aligned on the way forward

### CODE REVIEW

**Comment by tylerlittlefield** [comment]
@dmi3kno I deleted the branch because I don't know what I'm doing with resolving these merge conflicts. 

Could you submit the PR again. I think I’ve just got to go back and resolve each conflict one by one. Not sure if there is an automatic solution.

**Comment by dmi3kno** [comment]
Whenever you wake up and ready to go some damage. Could you create a new branch off of `master` which would be called `dev-rx_string`. Your `dev` branch is ahead of `master` and I hate to rebase again.

**Comment by tylerlittlefield** [comment]
Yeah sorry about that. I will be creating a new branch and then resolve all the merge conflicts today.

**Comment by dmi3kno** [comment]
No, just create a branch from `master` and I will PR into it. There will be no merge conflicts

**Comment by tylerlittlefield** [comment]
dev-rx_string branch created from master

**Pull request merged**
